### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by HukuToc2288** [avissian/banner#2]
webtlo: v2.9.9-alpha12-dev1
client: qbittorrent 4.6.0 alpha 1
OS: Ubuntu 22.04.2 LTS x86_64 5.15.0-60-generic

Steps to reproduce:
Run: `./banner --tlo_config=<tlo_data_dir>/config.ini --ban_list=banlist.txt`

Output
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5ba03c]

goroutine 1 [running]:
gopkg.in/ini%2ev1.(*Key).String(...)
	/go/pkg/mod/gopkg.in/ini.v1@v1.67.0/key.go:180
github.com/avissian/banner/tlo_config.loadTracker(0xc000098280?)
	/github/workspace/tlo_config/tlo.go:191 +0x27c
github.com/avissian/banner/tlo_config.(*ConfigT).Load(0xc0000d9d68, {0x7ffd8348780a?, 0x0?})
	/github/workspace/tlo_config/tlo.go:86 +0x246
main.tloConfig({0x7ffd8348780a?, 0xc0000061a0?}, {0x7ffd83487841, 0xb})
	/github/workspace/main.go:115 +0x6d
main.main()
	/github/workspace/main.go:158 +0x137
```

webtlo and qbittorrent configured correctly

**Comment by avissian** [comment]
https://github.com/avissian/banner/releases/tag/v0.0.3
